def hexskip(text):
	text=text.replace('\x00',"")
	text=text.replace('\x01',"")
	text=text.replace('\x02',"")
	text=text.replace('\x03',"")
	text=text.replace('\x04',"")
	text=text.replace('\x05',"")
	text=text.replace('\x06',"")
	text=text.replace('\x07',"")
	text=text.replace('\x08',"")
	text=text.replace('\x09',"")
	text=text.replace('\x0a','')
	text=text.replace('\x0b','')
	text=text.replace('\x0c','')
	text=text.replace('\x0d','')
	text=text.replace('\x0e','')
	text=text.replace('\x0f','')
	text=text.replace('\x10',"")
	text=text.replace('\x11',"")
	text=text.replace('\x12',"")
	text=text.replace('\x13',"")
	text=text.replace('\x14',"")
	text=text.replace('\x15',"")
	text=text.replace('\x16',"")
	text=text.replace('\x17',"")
	text=text.replace('\x18',"")
	text=text.replace('\x19',"")
	text=text.replace('\x1a','')
	text=text.replace('\x1b','')
	text=text.replace('\x1c','')
	text=text.replace('\x1d','')
	text=text.replace('\x1e','')
	text=text.replace('\x1f','')
	return text
	
